name: Microservices CI

on:
  push:
    branches:
      - '**'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
    strategy:
      matrix:
        service: [auth-service, blog-service, comment-service, profile-service]
    defaults:
      run:
        working-directory: ${{ matrix.service }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: docker build -t ${{ matrix.service }}:latest .

  integration-tests:
    runs-on: ubuntu-latest
    needs: test-and-build
    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install root dependencies
        run: npm install

      - name: Run Blog Service integration test
        run: npm run test:blog

      - name: Run Comment Service integration test
        run: npm run test:comment

      - name: Run Profile Service integration test
        run: npm run test:profile
